spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gado_db
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true