name: CI/CD Pipeline - Gado Backend

on:
  push:
    branches:
      - main
      - dev  # <-- Monitora as duas
    paths:
      - 'gado-backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilar e rodar os testes
        run: |
          cd gado-backend
          mvn clean install

      - name: Disparar Deploy de Produção (main)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Avisando o Render de Produção..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Disparar Deploy de Desenvolvimento (dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "Avisando o Render de Desenvolvimento (Dev)..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_DEV }}"